# Generated by Django 2.1.1 on 2018-09-28 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tqts_data',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('check_num', models.IntegerField()),
                ('stuno', models.CharField(max_length=32)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('yaw', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('sim', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('status_present', models.CharField(blank=True, max_length=32, null=True)),
                ('lessonid', models.CharField(max_length=32)),
                ('deviceid', models.CharField(max_length=32)),
                ('kpoint', models.CharField(blank=True, max_length=666, null=True)),
                ('box', models.CharField(blank=True, max_length=666, null=True)),
                ('gdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tqts_data',
                'managed': False,
            },
        ),
    ]
