# Generated by Django 2.1.1 on 2018-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('reader', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
