# Generated by Django 2.1.1 on 2018-09-28 02:02

import diango_demo.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu_face_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baidu_face_search',
            old_name='faceToken',
            new_name='face_token',
        ),
        migrations.AddField(
            model_name='baidu_face_search',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baidu_face_search',
            name='id',
            field=models.UUIDField(default=diango_demo.tools.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='baidu_face_search',
            table='baidu_face_search',
        ),
    ]
